source 'https://github.com/CocoaPods/Specs.git'

target 'SVSAVPlayerSample' do

  use_frameworks!
  platform :ios, '9.0'

  project 'SVSAVPlayerSample.xcodeproj'

  pod 'Smart-Instream-SDK', '7.13.0'

end
