source 'https://github.com/CocoaPods/Specs.git'

target 'SVSAVPlayerSample' do

  use_frameworks!
  platform :ios, '11.0'

  project 'SVSAVPlayerSample.xcodeproj'

  pod 'Smart-Instream-SDK', '~> 7.19.1'

end
