source 'https://github.com/brightcove/BrightcoveSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'SVSBrightcoveSample' do

  use_frameworks!
  platform :ios, '11.0'

  pod 'Brightcove-Player-Core/XCFramework', '6.10.2'
  pod 'Smart-Instream-SDK', '~> 7.21.0'

end
