source 'https://github.com/brightcove/BrightcoveSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'SVSBrightcoveSample' do

  use_frameworks!
  platform :ios, '9.0'

  pod 'Brightcove-Player-Core/dynamic'
  pod 'Smart-Instream-SDK', '7.7.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end

end
