source 'https://github.com/CocoaPods/Specs.git'

target 'SVSTVSample' do

  use_frameworks!
  platform :tvos, 9.0
  
  pod 'Smart-Instream-TV-SDK', '7.7.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end

end
